/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.thunlp.lm.srilm;

public class SRILMLanguageModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SRILMLanguageModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SRILMLanguageModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SRILMJNI.delete_SRILMLanguageModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SRILMLanguageModel(String filename, long order) {
    this(SRILMJNI.new_SRILMLanguageModel(filename, order), true);
  }

  public long getWordIndex(String arg0) {
    return SRILMJNI.SRILMLanguageModel_getWordIndex(swigCPtr, this, arg0);
  }

  public long getVocabNone() {
    return SRILMJNI.SRILMLanguageModel_getVocabNone(swigCPtr, this);
  }

  public float prob(long word, SWIGTYPE_p_unsigned_int reverse_context) {
    return SRILMJNI.SRILMLanguageModel_prob(swigCPtr, this, word, SWIGTYPE_p_unsigned_int.getCPtr(reverse_context));
  }

  public long get_order() {
    return SRILMJNI.SRILMLanguageModel_get_order(swigCPtr, this);
  }

}
